[package]
name = "todo-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
futures = "0.3.27"
postgres = "0.19.4"
serde = "1.0.156"
tokio = "1.26.0"

