[target.x86_64-unknown-linux-musl]
pre-build = ["rm /etc/ld-musl-x86_64.path && apt-get update && apt-get install -y openssl build-essential libssl-dev musl && apt-get install -y musl-dev && apt-get install -y musl-tools"]
